### ISSUE TITLE
Docket Cache causing a Fatal Error in Site Health when used with Performance Lab

### ISSUE THREAD

**Issue by bobbyferran** [nawawi/docket-cache#21]
Hello,

I am just writing to inform you that Docket Cache is causing a fatal error on the site health page when the user also has performance lab installed. This issue was sent to performance lab as well and it was determined - In core, wp_load_alloptions() returns strings, with arrays and objects being serialized. However, some object cache plugins (namely Docket Cache) may return mixed values, including arrays and objects. This hardens perflab_aao_autoloaded_options_size() to account for this by ensuring all array and object values are serialized before computing the string length.' 

This is issue #1238 on Github under performance lab.

**Comment by bobbyferran** [comment]
These are the details about the original error on my site:
Error Details
=============
An error of type E_ERROR was caused in line 106 of the file /home3/flowergu/public_html/wp-content/plugins/performance-lab/includes/site-health/audit-autoloaded-options/helper.php. Error message: Uncaught TypeError: strlen(): Argument #1 ($string) must be of type string, array given in /home3/flowergu/public_html/wp-content/plugins/performance-lab/includes/site-health/audit-autoloaded-options/helper.php:106
Stack trace:
#0 /home3/flowergu/public_html/wp-content/plugins/performance-lab/includes/site-health/audit-autoloaded-options/helper.php(22): perflab_aao_autoloaded_options_size()
#1 /home3/flowergu/public_html/wp-admin/includes/class-wp-site-health.php(194): perflab_aao_autoloaded_options_test()
#2 /home3/flowergu/public_html/wp-admin/includes/class-wp-site-health.php(145): WP_Site_Health->perform_test('perflab_aao_aut...')
#3 /home3/flowergu/public_html/wp-includes/class-wp-hook.php(324): WP_Site_Health->enqueue_scripts('site-health.php')
#4 /home3/flowergu/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#5 /home3/flowergu/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /home3/flowergu/public_html/wp-admin/admin-header.php(118): do_action('admin_enqueue_s...', 'site-health.php')
#7 /home3/flowergu/public_html/wp-admin/site-health.php(96): require_once('/home3/flowergu...')
#8 {main}
thrown

**Comment by nawawi** [comment]
Hi there,

You may do a quick fix by adding maybe_serialize:

File: performance-lab/includes/site-health/audit-autoloaded-options/helper.php
Line: 106

Before:
```php
foreach ( $all_options as $option_name => $option_value ) {
    $total_length += strlen( $option_value );
}
```

Fix:
```php
foreach ( $all_options as $option_name => $option_value ) {
    $total_length += strlen( maybe_serialize($option_value));
}
```

Thanks.
